### ISSUE TITLE
Allow making analysis public when locked

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#114]
When an analysis is locked, the user should still be able to make it public.

**Comment by skept** [comment]
@adelavega Is the `private` field the only exception to the rule of not allowing any updates once the analysis is no longer in `DRAFT` mode? If we go the route of making exceptions to this rule, fields like description and name also seem harmless enough.

**Comment by adelavega** [comment]
That seems reasonable... However, I think what I'll do is reject any other changes if they come and return an object with only the exception fields changed
