### ISSUE TITLE
Prominently display hash id

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#118]
The hash id is not displayed to the user, but it is actually quite important because it is the Id they will use to execute the analysis. Let's display this ID to users relatively prominently (if we can find a nice place for it), or at least when the analysis becomes compiled under "Status'

**Comment by skept** [comment]
For now I can add it right next to the lock icon.

**Comment by adelavega** [comment]
cool. also would be cool to display it in the browser (when you can see multiple analyses)
