### ISSUE TITLE
Import dataset from DataLad/git-annex

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#14]
Would be cool if instead of needing to have a specific dataset on hand, you could just specific a datalad dataset to import, and it would download just what is required and import. 

Should we need the actual event.tsv files, then we need the actual dataset, rather than just a JSON description of it. But thanks to git-annex, we can just pull the files we need (i.e. no imaging data).

**Comment by adelavega** [comment]
Population scripts using python-datalad `install` and `AutomagicIO` are implemented (and it seems to work) but forrest dataset on DataLad does *not* have stimuli, thus can't fully test.

**Comment by tyarkoni** [comment]
paging @mih...

**Comment by mih** [comment]
Sorry, I have the world on hard-ignore. Big measurement tomorrow, will
resurface next week...

**Comment by adelavega** [comment]
Looks like this should be not be an issue since I can just clone from the github repo using datalad, rather than having to clone from openfmri, which is outdated because it is difficult to update. Yay Datalad!

**Comment by adelavega** [comment]
So far, seems to work, but monkey patched open call leads to occasional problems. Dealing on a case by case basis.

**Comment by adelavega** [comment]
Monkey patching seems better, not need to work on persisting data on local disk as to not to have to re-download each time. This relates to implementing a meta-dataset.

**Comment by adelavega** [comment]
Closed with #73
