### ISSUE TITLE
Additional bundle endpoints

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#142]
Currently, bundle is very verbose and user-unfriendly.

Add endpoints for json and tsv representations of the design matrix, and separate from main bundle endpoint.

Also, add filelist endpoint as json

**Comment by adelavega** [comment]
Actually reorganize as follows:

- `analysis` endpoint returns full analysis spec, but with only ids for 
- `design_matrix` as both `/tsv` and `/json`. Store tsv on disk on compilation. Should not change after successful compilation. Returns `404` if not compiled.
- `images` returns list of preprocessed images required (relative path)
- `bundle` is tarball w/ all 3 (full analysis spec, design_matrix and image list)

Possible also include a `summary` human readable endpoint or a more comprehensive `analysis` end point with nested fields (e.g. `dataset.dataset_address`, `predictor.name`)

**Comment by qmac** [comment]
Let's also keep https://docs.google.com/document/d/1bhFwSe4kqPsgqcjGp3XSM6Y1N2eAMi6xZrUp_c3mPGg/edit?ts=59ce704f in sync with this.

**Comment by adelavega** [comment]
Closed
