### ISSUE TITLE
Refactor populate scripts to use BIDSVariableCollection

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#187]
Given that `BIDSVariableCollection` should allow one to read in all of the variables in a BIDS project, including event files, physio, and "external" (e.g. manually annotated features), it makes sense to use this code in the population scripts rather than doubling effort. Especially given that neuroscout doesn't ingest physio or external features yet. 

Thus, ingestion would really convert BIDSVariables into a db representation. 
Note: this requires BIDSVariableCollection to support loading "external" events. @tyarkoni 

It's possible that this might cause more friction than is worth though, and some code duplication is acceptable.

**Comment by tyarkoni** [comment]
Per INCF/pybids#101, we should definitely try to address this inside pybids if possible.

**Comment by adelavega** [comment]
Add "source" to BIDSVariableCollection for ingesting physio etc & Predictor in db
And use BIDSVariableCollection to read in other types of events

**Comment by adelavega** [comment]
Closed w #191
