### ISSUE TITLE
Word onset feature

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#228]
To create a word onset feature, maybe a custom Extractor would be a good idea, so that the logic remains the same? Or perhaps could add it in as a "postprocessing" function, like what was previously being worked on.

**Comment by tyarkoni** [comment]
I think the `ComplexTextExtractor` may be what you're looking for.

**Comment by tyarkoni** [comment]
Oh, I see--you mean you want the `onset` value in the feature column? We could do that, I suppose.

**Comment by tyarkoni** [comment]
On second thought, I think postprocessing option is probably the way to go here.

**Comment by adelavega** [comment]
Yeah I actually just want a dummy regressor for word onset, without having to build in something "custom" for this. I think I may be able to just use the DummyExtractor, since it will just put a 1 wherever there is a word stimulus. 

I was also suggesting that I could maintain a set of custom Extractors (derived from pliers) for such idiosyncratic uses that would not be useful more generally. The only reason this one is a bit weird is its going from Stim -> Feature. And "postprocessing" was going to go from Feature -> Derived feature. Although I could tweak that.

**Comment by tyarkoni** [comment]
The `ComplexTextExtractor` gives you back a feature. The feature is the identity of the word (it's called `'word'`), but you can just take the `onset` column and use that.

**Comment by adelavega** [comment]
TODO: Fix non-unique filename problem on extraction of ComplexTextFeature.
