### ISSUE TITLE
Compile route timeout

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#239]
It seems that if a response takes too long, flask will kill the worker. In this case, if there are too many predictors, the `/compile` route will take too long, and timeout. It's also annoying how long this takes, so we need to work on a way to speed up the queries used in `compile` or to push them to a background job, and return `200` immediately when a compile request has been made.

**Comment by adelavega** [comment]
Ah, it seems as if the `[CRITICAL] WORKER TIMEOUT` error might be a gunicorn problem, and perhaps due to insufficient RAM?

**Comment by adelavega** [comment]
One solution would be to increase the timeout time: https://serverfault.com/questions/490101/how-to-resolve-the-gunicorn-critical-worker-timeout-error

But its best if we can avoid long running requests.

**Comment by rwblair** [comment]
http://docs.gunicorn.org/en/stable/settings.html#timeout

Looks like the default limit is 30 seconds.
