### ISSUE TITLE
Mailgun A or MX records are incorrect

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#248]
```
Failed: no-reply@neuroscout.org → delavega@utexas.edu 'Welcome to Neuroscout!' Server response: 553 5.1.8 Domain of sender address <bounce+ae49a3.2923e-delavega=utexas.edu@send.neuroscout.org> does not exist or has no A or MX records
```

**Comment by tyarkoni** [comment]
What's the intended behavior?

**Comment by adelavega** [comment]
This is an error from Mailgun itself. Which means no mail is currently being sent, because the neuroscout domain is set up incorrectly. 

Oddly, it was working a little while ago, as Ross signed up and verified his email. My guess is what once we changed to `alpha.neuroscout.org` something went wrong in the domain set up, and the A/MX records don't match up. Although, I'm not sure why that would be, but I can't think of anything else that has changed recently.

**Comment by tyarkoni** [comment]
Can you see if the TXT records mailgun creates have changed? You can paste them on slack again

**Comment by tyarkoni** [comment]
Oh, it's possible the TXT records need to be generated for a specific (sub)domain, and we'd need to explicitly tell mailgun we need records for alpha.neuroscout.org. Maybe look into it on the mailgun side.

**Comment by adelavega** [comment]
Looks good now
