### ISSUE TITLE
Trigger creation of nipype workflows & analysis bundle

### ISSUE THREAD

**Issue by adelavega** [PsychoinformaticsLab/neuroscout#46]
Upon locking of an analysis.
- Ensure these are async calls. 
-  Generate graphs  
- Add counts of workflow retrievals / downloads tables - timestamp every time someone retrieves a workflow.

**Comment by adelavega** [comment]
Also create new event files (w/ only selected predictors).

**Comment by adelavega** [comment]
Make sure file references are correct in db (i.e. to niftis in BIDS dataset, but also to newly created event files). This way grabbids is not necessary in the actual workflow as individual files are pointed to. If it turns out to be necessary (i.e. structural files?) that's fine.

**Comment by qmac** [comment]
This issue was moved to PsychoinformaticsLab/neuroscout-cli#1
