### ISSUE TITLE
Can't clone pending analysis

### ISSUE THREAD

**Issue by skept** [PsychoinformaticsLab/neuroscout#71]
Getting `{ "message": "Only locked analyses can be cloned"}` when I try to clone an analysis with status == 'PENDING'

**Comment by adelavega** [comment]
I think that's expected behavior. Only COMPILED datasets should be cloneable (since PENDING could potentially fail, and thus need to be editable, and thus not be clonable in the future)

**Comment by adelavega** [comment]
Actually I'll reopen this to add that the message should be more specific and say only "compiled" analyses can be cloned, to have consistent terminology.

**Comment by skept** [comment]
I see. What if my analysis is still in DRAFT or PENDING but I want to create a similar but slightly different version of the analysis? Is the clone feature supposed to address this use case too or should I just create a new analysis from scratch? Not sure how common this would be in practice.

**Comment by tyarkoni** [comment]
Just talked it over with @adelavega and we agree that a user should be able to clone any of their own analyses, regardless of status, but should only be able to clone other users' analyses if they're COMPILED.
