### ISSUE TITLE
Change analysis['transformations'] type to array

### ISSUE THREAD

**Issue by skept** [PsychoinformaticsLab/neuroscout#83]
Currently the the API route to save the analysis expects an object for `transformations` and return a 422 response:

```javascript
{
  "message": {
    "transformations": [
      "Not a valid mapping type."
    ]
  }
}
```

**Comment by adelavega** [comment]
Array of transformation objects with the following structure:

    {
       "name" : "transformation_name",
       "inputs" : ["predictor_name", "predictor_name2"],
       "parameters" : [{"name : "parameter_one", "value" : true}]
    }
