### ISSUE TITLE
Global configuration options that override per-predictor configurations

### ISSUE THREAD

**Issue by skept** [PsychoinformaticsLab/neuroscout#91]
From the meeting notes:

> The "global configuration" section should add the convolution and temporal derivative options. Then the per-predictor configuration options can override the global ones when specified on a separate sub-tab (or they can just be hidden by default, as per-predictor configuration is rare, though it does happen)
> Maybe give a warning that changing the global config may overwrite per-predictor config

**Comment by skept** [comment]
Also add a checkbox/collapse to hide/show per-predictor configurations

**Comment by adelavega** [comment]
For now, we're going to disable per predictor options.
