### ISSUE TITLE
For analyses with no transformations return [] instead of [{}]

### ISSUE THREAD

**Issue by skept** [PsychoinformaticsLab/neuroscout#99]
@adelavega The frontend code currently assumes that if the transformations array is non-empty, any element is a valid transformation (i.e. at least with a transformation name and an input array)

**Comment by adelavega** [comment]
I just tested this and it does only return an empty array. I think the example value has the empty object to indicate the class of data that goes into the array.

**Comment by skept** [comment]
@adelavega I looked into this some more. Looks like for new analyses it behaves as you described. But for existing analyses that were migrated the server returns [{}]. As a workaround I added a quick check to filter out any transformations with missing names, so it's a non-issue now:

```javascript
transformations: data.transformations.filter(xform => xform.name)
```
